services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxrecord_api
    ports:
      - "5097:5097"
    networks:
      - taxrecord_network

  frontend:
    build:
      context: ./Front-End/TaxRecord-frontend
      dockerfile: Dockerfile
    container_name: taxrecord_frontend
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - taxrecord_network

networks:
  taxrecord_network:
    driver: bridge
